### ISSUE TITLE
Issue with .bmods after uninstalling mods and verifying files.

### ISSUE THREAD

**Issue by Malitahj** [Farbigoz/BhModloader#2]
Fatal Error:

Traceback (most recent call last):
  File "run.py", line 326, in <module>
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\BrawlhallaModloaderApp_0.3\main.py", line 665, in queueUrl
  File "E:\BrawlhallaModloaderApp_0.3\main.py", line 730, in urlImport
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Program Files\\ModLoader\\Mods\\_mod.archive'

**Comment by Malitahj** [comment]
Closing. Fixed after deleting the mod folder and reopening Loader.exe . That's my solution for now.
